# Generated by Django 3.1.6 on 2021-02-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='test',
            new_name='details',
        ),
    ]
